name: Android NDK Release Build

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compile-sdk: [36]
        build-tools: [36.0.0]
        commandlinetools-download-url: ['https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip']
        ndk-version: [28.2.13676358]
        cmake-version: [4.0.3]
        root-project-path: [./]

    steps:
    - uses: actions/checkout@v4
    - name: setup ubuntu
      run: |
        sudo apt-get --quiet update --yes
        sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - name: setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: download Android SDK
      working-directory: ${{ matrix.root-project-path }}
      run: |
        wget --quiet --output-document=android-sdk.zip ${{ matrix.commandlinetools-download-url }}
        unzip -d android-sdk-linux android-sdk.zip
        sudo mkdir -p /root/.android
        sudo touch /root/.android/repositories.cfg
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "platforms;android-${{ matrix.compile-sdk }}" >/dev/null
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "platform-tools" >/dev/null
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "build-tools;${{ matrix.build-tools }}" >/dev/null
        export ANDROID_SDK_ROOT=$PWD
        export PATH=$PATH:$PWD/platform-tools/
        chmod +x ./gradlew
        set +o pipefail
        yes | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. --licenses
        set -o pipefail
    - name: install Android NDK
      working-directory: ${{ matrix.root-project-path }}
      run: android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. --install "ndk;${{ matrix.ndk-version }}" "cmake;${{ matrix.cmake-version }}"
    - name: Setup Build Configs
      working-directory: ${{ matrix.root-project-path }}
      env:
        ANDROID_RELEASE_BASE64_KEY: ${{ secrets.ANDROID_RELEASE_BASE64_KEY }}
        ANDROID_RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
      run: |
        echo ${ANDROID_RELEASE_BASE64_KEY} | base64 -d > ./release-application-key
        echo "RELEASE_STORE_FILE=`pwd`/release-application-key" >> ./local.properties
        echo "RELEASE_STORE_PASSWORD=${ANDROID_RELEASE_KEY_PASSWORD}" >> ./local.properties
        echo "RELEASE_KEY_ALIAS=key0" >> ./local.properties
        echo "RELEASE_KEY_PASSWORD=${ANDROID_RELEASE_KEY_PASSWORD}" >> ./local.properties
    - name: Android Release Apk Build
      working-directory: ${{ matrix.root-project-path }}
      run: ./gradlew assembleRelease
    - name: Android Release aab Build
      working-directory: ${{ matrix.root-project-path }}
      run: ./gradlew bundleRelease
    - uses: actions/upload-artifact@v4
      with:
        name: outputs
        path: ${{ matrix.root-project-path }}/app/build/outputs/